/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaboresRouteImport } from './routes/sabores'
import { Route as RecomendadorRouteImport } from './routes/recomendador'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'

const SaboresRoute = SaboresRouteImport.update({
  id: '/sabores',
  path: '/sabores',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendadorRoute = RecomendadorRouteImport.update({
  id: '/recomendador',
  path: '/recomendador',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/recomendador': typeof RecomendadorRoute
  '/sabores': typeof SaboresRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/recomendador': typeof RecomendadorRoute
  '/sabores': typeof SaboresRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/recomendador': typeof RecomendadorRoute
  '/sabores': typeof SaboresRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/contacto'
    | '/recomendador'
    | '/sabores'
    | '/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/contacto'
    | '/recomendador'
    | '/sabores'
    | '/producto/$slug'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/contacto'
    | '/recomendador'
    | '/sabores'
    | '/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  RecomendadorRoute: typeof RecomendadorRoute
  SaboresRoute: typeof SaboresRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sabores': {
      id: '/sabores'
      path: '/sabores'
      fullPath: '/sabores'
      preLoaderRoute: typeof SaboresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendador': {
      id: '/recomendador'
      path: '/recomendador'
      fullPath: '/recomendador'
      preLoaderRoute: typeof RecomendadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  RecomendadorRoute: RecomendadorRoute,
  SaboresRoute: SaboresRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
